# This file was generated by GoReleaser. DO NOT EDIT.
class Getmoe < Formula
  desc "cli tool for boorus"
  homepage "https://github.com/leonidboykov/getmoe"
  url "https://github.com/leonidboykov/getmoe/releases/download/v0.4.0/getmoe_0.4.0_macOS_x86_64.tar.gz"
  version "0.4.0"
  sha256 "3432fdb21c5cc7ec5abe93bf0d133d7220c18e991c61eee3bfc8385352767406"

  def install
    bin.install "getmoe"
  end

  test do
    system "#{bin}/getmoe -v"
  end
end
