# This file was generated by GoReleaser. DO NOT EDIT.
class Gosling < Formula
  desc "HTML redirects generator"
  homepage "https://leonidboykov.github.io/gosling/"
  version "0.1.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/leonidboykov/gosling/releases/download/v0.1.7/gosling_0.1.7_macOS_x86_64.tar.gz"
    sha256 "dd8e6cf5a0461dd408f18289ee7ed3cdffd98937f903a8ad7efae4a53a91c61c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/leonidboykov/gosling/releases/download/v0.1.7/gosling_0.1.7_Linux_x86_64.tar.gz"
      sha256 "1ee79cce855ddd4adc17e8289f570198e3e06949b8033aedc38b7c2ee67d01d0"
    end
  end

  def install
    bin.install "getmoe"
  end

  test do
    system "#{bin}/gosling -v"
  end
end
