# This file was generated by GoReleaser. DO NOT EDIT.
class Gosling < Formula
  desc "HTML redirects generator"
  homepage "https://leonidboykov.github.io/gosling/"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/leonidboykov/gosling/releases/download/v0.2.0/gosling_0.2.0_macOS_x86_64.tar.gz"
    sha256 "1988ab308fdc9eff38712edb37e9c7d938a2cfb98cf07f431d377e60f1371f62"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/leonidboykov/gosling/releases/download/v0.2.0/gosling_0.2.0_Linux_x86_64.tar.gz"
      sha256 "60a09266b865f0692a11540ab5a7b9090cc3fb9ecde7911071ed3d2093576497"
    end
  end

  def install
    bin.install "getmoe"
  end

  test do
    system "#{bin}/gosling -v"
  end
end
